import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import "./globals.css";
import UserSync from "@/components/UserSync";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SMILO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<ClerkProvider
appearance={{
    variables: {
      colorPrimary: "#b3b3b3",
      colorBackground: "#0f0f0f",
      colorInputBackground: "#181818",
      colorText: "#f5f5f5",
      colorTextSecondary: "#b3b3b3",
    },
    elements: {
      socialButtonsBlockButton: {
        backgroundColor: "#ffffff",
        color: "#000000",
        border: "1px solid #e5e7eb",
      },
      socialButtonsBlockButtonText: {
        color: "#000000",
        fontWeight: "500",
      },
      socialButtonsBlockButtonIcon: {
        filter: "invert(0)",
      },
    },
  }}

>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <UserSync/>
        {children}
      </body>
    </html>
</ClerkProvider>
  );
}
